[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "voltwire"
dynamic = ["version"]
dependencies = [
    "Django>=3.2",
]

[tool.setuptools_scm]
write_to = "voltwire/_version.py"